### ISSUE TITLE
Producer: routing_key works only for URL parameters

### ISSUE THREAD

**Issue by lennondtps** [krakend/krakend-amqp#21]
Hello, 
Following the documentation here https://www.krakend.io/docs/backends/amqp-producer/#routing_key the routing key is expected to work with static values.

Unfortunately, this functionality is not supported by the code.

I am willing to open a Pull Request to make the code supporting this. Are you ok with including this functionality?

@kpacha @alombarte is there any alternative to make use of static routing values?

**Comment by alombarte** [comment]
Hello @lennondtps 

Thanks for your offering. From a product perspective, the functionality sounds good. If the code ends up in the repository or not depends on the implementation and efficiency of the solution.

Feel free to send a PR for review

**Comment by lennondtps** [comment]
Hello @alombarte ! Feel free if you have any comments/suggestions for my PR --> https://github.com/krakend/krakend-amqp/pull/22
